### ISSUE TITLE
Verify app

### ISSUE THREAD

**Issue by ovari** [flathub/eu.betterbird.Betterbird#80]
It would be great to have this app as a verified app on [Flathub](https://flathub.org/apps/eu.betterbird.Betterbird).

Can this app please be [verified on Flathub](https://flathub-docs.vercel.app/docs/for-users/verification)?

Thank you

**Comment by mfschumann** [comment]
Sure, why not. Do you know what is the process to get the app verified?

**Comment by ovari** [comment]
> Sure, why not. Do you know what is the process to get the app verified?

Does this help:
https://flathub-docs.vercel.app/docs/for-app-authors/verification

Thank you

**Comment by ovari** [comment]
There is also a discussion about verifying MMEX at https://github.com/flathub/org.moneymanagerex.MMEX/issues/3 which might help.

**Comment by mfschumann** [comment]
Thanks, I have started the verification process. In order to complete verification, I need the approval of the app developer. @Betterbird Would you mind to express your approval for uploading Betterbird to flathub by adding the page
https://betterbird.eu/.well-known/org.flathub.VerifiedApps.txt 
containing the following token:
2adca826-bbf4-427e-9fe2-bee49d8660b2

**Comment by Betterbird** [comment]
Done. I hope a Linux linebreak (LF) at the end of the string is OK, if not, let us know.

**Comment by mfschumann** [comment]
Thanks, the app has now been verified. Closing this issue.
